In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pip install koreanize-matplotlib

Collecting koreanize-matplotlib
  Downloading koreanize_matplotlib-0.1.1-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 17.7 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from koreanize-matplotlib) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.4.4)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (3.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->koreanize-matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.16.0)
Installing collected packages: koreanize-matplotlib
Successfully installed koreanize-matplotlib-0.1.1

# 파이썬 기초 1

## 1) 변수
변수 = 자료를 넣는 상자
어떤 자료를 담느냐에 따라 상자의 모양 / 성격(자료형)이 달라짐

In [ ]:
a = 1
b = 3.144156465153
c = "ㄱ" # str 문자형은 반드시 따옴표를 넣어야한다

print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>

* 문자 1개 = 문자
* 문자 2개 이상 = 문자열
* 문자열은 순서가 있고 번호를 불러 그 번호에 해당하는 문자를 꺼내올 수 있다.
  * 꺼내오는 방법은 변수명[번호]
  * 파이썬은 0번부터 시작한다

In [ ]:
d = 'python'

print(d)

python

In [ ]:
type(d)

str

In [ ]:
print('Hello World!')

Hello World!

## 변수 여러개를 한번에 만들기
* 변수에는 1개의 자료만 들어간다.
* 변수에 다른 자료를 넣으면 이전 자료는 사라지게 된다.

In [ ]:
x,y,z = 10,20,30
del(z)

In [ ]:
print(x)

10

In [ ]:
print(y)

20

In [ ]:
print(z)

NameError: ignored

## 키보드 값을 입력 받아 변수에 저장하기

In [ ]:
num = int(input('갑 입력>>'))
print(num)

갑 입력>>10
10

### 형 변환
* 데이터 타입을 변환 시켜준다
* int - 정수 : int(변수명)
* float 실수 : float(변수명)
* str 문자/문자열 : str(변수명)

In [ ]:
num = int(num) # int 정수로 형 변환

In [ ]:
num2 = 20
num2 = float(num2)

In [ ]:
type(num2)

float

In [ ]:
# num을 str 값으로 변환

num = str(num)
print(num)
type(num)

10

str

In [ ]:
hap2 = num + num2 #num은 정수(int),num2는 실수
# 더하면 우선순위는 실수이기 때문에 실수 값이 우선한다

## 문자와 문자열
* 문자형 변수에는 단어 뿐만 아니라 문장도 들어갑니다

In [ ]:
s = '문자형 변수'

In [ ]:
s3 = "it's python"

In [ ]:
s4 = 'it"s python'

In [ ]:
s4 = '이것은 "파이썬" 입니다.'

In [ ]:
s5 = '''
안녕하세용
'''

In [ ]:
DataUrl = 'https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv'
df = pd.read_csv(DataUrl,encoding='euc-kr')

In [ ]:
s6 =  """
  문자형 변수에는 단어 뿐만 아니라
  문장도 들어갑니다.
"""

In [ ]:
print(s6)

  문자형 변수에는 단어 뿐만 아니라
  문장도 들어갑니다.

### 리스트형 변수 - 데이터 분석에서 가장 많이 사용하는 자료형 1

* 모든 데이터 타입(정수,실수,문자열,리스트,딕셔너리)의 자료를 넣을 수 있다.
* 리스트 자료형은 순서기 있는 자료형이다
* 순서가 있는 자료형은 index(번호)로 자료를 꺼낼 수 있다.
* 리스트 자료형식은 [자료1,자료2,자료3] 형식을 만든다

In [ ]:
random_list = ['김치','치즈',12,13,1.25,333,'aaa']

random_list[::-1]

['aaa', 333, 1.25, 13, 12, '치즈', '김치']

### 슬라이싱 : 리스트에서 범위를 지정해 자료를 여러개 가져오는 법
* 변수명[시작번호:끝번호 바로 앞까지 범위]
* 변수명[시작번호:끝번호 바로 앞까지:범위간격]

In [ ]:
L2 = [1,2,[3,4,5],6,7,8]

In [ ]:
L2[2][1]

4

In [ ]:
L3 = [1,2,[3,4,5,[9,10,11]],6,7,8]

In [ ]:
L3[2][3][1]

10

## 튜플
* 튜플을 리스트와 거의 동일
* 차이점은 리스트 대괄호 [] 튜플은 () 괄호로 포장
* 리스트는 자료의 변경이 가능하나 튜플은 변경이 불가능하다
* 리스트보다 속도가 빠르기 때문에 쓰인다

In [ ]:
T = (1,2,3,[4,5,6],(7,8,9,[10,11,12]))

T[4][3][0]

10

In [ ]:
L3[0] = 10
L3

[10, 3, [3, 4, 5, [9, 10, 11]], 6, 7, 8, 15]

In [ ]:
L3.insert(1,3)

In [ ]:
L3.pop(3)

6

# 딕셔너리 ,JSON이라고도 함
데이터분석에서 가장 많이 사용되는 자료형2

* key : value 형태의 자료형으로 나중에 API를 이용해서 자료를 수집하면 대부분 JSON 형태로 받게된다.

* 변수명 = {key:value, ....}

* Value = 모든 자료형이 올 수 있다.

In [195]:
create_dic = {'연월': '20230804','국가':'대한민국','방문자수':'10000'}

In [217]:
create_dic['연월']

'20230804'

In [231]:
create_dic2 = {'년월':[2021,2022,2023],'일':[1,2,3,4,5,6,7,8,9,10],'국가':{'국가명':['미국','대한민국']}}

create_dic2['년월'][0]
create_dic2['일'][1]
create_dic2['국가']['국가명'][1]

'대한민국'

In [ ]:
df.head()

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
0,22448,2018-01-01,제주시,도두동,32249.987,3418.266,102709.092,138377.345,39.556,29.167,5.0,0.0,2.5
1,22449,2018-01-01,제주시,외도동,213500.997,10341.172,112692.789,336534.958,32.900,30.900,5.0,0.0,2.5
2,22450,2018-01-01,제주시,이도2동,1212382.218,96920.834,541194.481,1850497.533,29.538,35.692,2.9,0.0,2.4
3,22451,2018-01-01,제주시,일도1동,33991.653,6034.253,72155.919,112181.825,30.000,23.500,2.9,0.0,2.4
4,22452,2018-01-01,서귀포시,대천동,155036.925,9403.969,150882.409,315323.303,41.583,14.375,5.1,0.0,2.3

In [ ]:
df.tail()

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
9616,32064,2020-04-30,서귀포시,표선면,228260.005,16891.732,152832.449,397984.186,44.514,34.054,18.1,0.0,4.70
9617,32065,2020-04-30,제주시,한림읍,459959.064,26007.122,249700.419,735666.605,48.609,61.377,18.0,0.0,4.35
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.00
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.50
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.80

In [ ]:
df.select_dtypes(exclude='object').columns #수치형 변수 추가

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

In [ ]:
df.select_dtypes(include='object').columns #범주형 변수 추가

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [ ]:
df.isnull().sum()

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

In [ ]:
df.describe()

,id,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
count,9621.000000,9.621000e+03,9621.000000,9621.000000,9.621000e+03,9621.000000,9621.000000,9621.000000,9621.000000,9621.000000
mean,27258.000000,3.174315e+05,35471.201510,195889.561802,5.487922e+05,41.109084,37.215873,13.550828,6.972426,2.753171
std,2777.487804,2.982079e+05,40381.214775,140706.090325,4.608802e+05,8.758631,12.993786,7.745515,27.617260,1.498538
min,22448.000000,9.305552e+03,1407.936000,11538.322000,2.225181e+04,24.333000,12.667000,-9.600000,0.000000,0.000000
25%,24853.000000,9.539939e+04,12074.498000,99632.153000,2.216910e+05,34.250000,27.889000,7.600000,0.000000,1.700000
50%,27258.000000,2.221105e+05,21960.928000,152805.335000,3.866935e+05,39.640000,34.500000,13.400000,0.000000,2.400000
75%,29663.000000,4.106671e+05,40192.032000,236325.109000,6.406918e+05,49.105000,46.176000,19.700000,1.500000,3.400000
max,32068.000000,1.364504e+06,263476.965000,723459.209000,2.066484e+06,103.000000,172.200000,30.400000,587.500000,13.333000

In [ ]:
df['거주인구']

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

In [ ]:
df.nunique()

id          9621
일자           803
시도명            2
읍면동명          41
거주인구        9621
근무인구        9621
방문인구        9621
총 유동인구      9621
평균 속도       3345
평균 소요 시간    4046
평균 기온       1324
일강수량         506
평균 풍속        439
dtype: int64

In [ ]:
df['읍면동명'].unique()

array(['도두동', '외도동', '이도2동', '일도1동', '대천동', '서홍동', '한경면', '송산동', '조천읍',
       '일도2동', '영천동', '예래동', '대륜동', '삼도1동', '이호동', '건입동', '중앙동', '삼양동',
       '삼도2동', '이도1동', '남원읍', '대정읍', '정방동', '효돈동', '아라동', '한림읍', '구좌읍',
       '용담1동', '오라동', '화북동', '연동', '표선면', '중문동', '성산읍', '안덕면', '천지동',
       '노형동', '동홍동', '용담2동', '봉개동', '애월읍'], dtype=object)

In [ ]:
DataUrl = 'https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv'
df = pd.read_csv(DataUrl)
Ans = type(df)

In [ ]:
df[df['quantity'] == 3].head(5)

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

In [ ]:
df.loc[df['quantity'] == 3].reset_index().head(5)

,index,order_id,quantity,item_name,choice_description,item_price
0,409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
1,445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
2,689,284,3,Canned Soft Drink,[Diet Coke],$3.75
3,818,338,3,Bottled Water,NaN,$3.27
4,850,350,3,Canned Soft Drink,[Sprite],$3.75

In [ ]:
df2 = df[['quantity' , 'item_price']]

In [ ]:
df2

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

In [ ]:
def charChange(x):
  result = x.split('$')[1]
  return float(result)

In [ ]:
df2['item_price'].apply(charChange)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [ ]:
def create_dictioanry():
  dictionary_list = []
  while True :
    Key = input('key 값 입력하세용>> ')
    user_prompt = {}
    if Key == 'q':
      break
    Value = input('value 값 입력하세용 >> ')
    user_prompt[Key] = Value
    dictionary_list.append(user_prompt)
  return dictionary_list

In [ ]:
create_dictioanry()

key 값 입력하세용>>밥먹기
value 값 입력하세용 >>저녁 9시
key 값 입력하세용>>q

[{'밥먹기': '저녁 9시'}]