##1. 람다 표현식(lambda expression)
* 함수 이름이 없는 함수 (익명함수)
* 간단한 함수 작성 하거나 다른 함수의 인수로, 함수를 넣을 때 사용한다.

In [2]:
# 10을 더하는 함수 기존
def func(x):
  return x + 10

In [3]:
func(5)

15

### 람다함수를 만든 뒤 호출하기

In [1]:
# 10을 더하는 함수

(lambda x: x+10)(5)

15

### 람다 함수를 변수에 넣고 변수에 인수를 넣어 호출하기

In [11]:
plus_five = (lambda x : x+5)

In [12]:
plus_five(5)

10

### 람다 표현식을 함수의 인수로 사용하기

In [13]:
def plus_ten(x):
  return x + 10

In [15]:
list(map(plus_ten,[1,2,3])) #맵으로 1,2,3을 매핑해서 함수에 넣어준 후에 , 리스트로 반환 시켜줌

[11, 12, 13]

In [16]:
list(map(lambda x : x + 10,[1,2,3])) #람다로 축약

[11, 12, 13]

### 람다 표현식의 조건부 표현식 사용하기
* 리스트 컴프리헨션을 이용하여 사용한다.

In [46]:
# 3의 배수만 문자열로 바꾸기

result = []

def three(*args):
  for i in args:

    if i % 3 == 0 :
      i = str(i)
      result.append(i)
    else:
      result.append(i)
  return result

In [71]:
a = three(*[1,2,3,4,5,6,7,8,9,10])

In [48]:
print(a)

[1, 2, '3', 4, 5, '6', 7, 8, '9', 10]

In [78]:
# 3의 배수만 문자열로 바꾸기

list(map(lambda x: str(x) if x % 3 ==0 else x,L))

[1, 2, '3', 4, 5, '6', 7, 8, '9', 10]

In [52]:
L = [1,2,3,4,5,6,7,8,9,10]

In [53]:
list(map(lambda x: str(x) if x % 3 == 0 else x,L))

[1, 2, '3', 4, 5, '6', 7, 8, '9', 10]

### map함수에 람다 표현식을 넣어서 여러개의 리스트 연산하기

In [54]:
a = [1,2,3,4,5]
b = [2,4,6,8,10]
c = [3,6,9,12,15]

In [55]:
list(map(lambda x,y,z: x * y * z,a,b,c))

[6, 48, 162, 384, 750]

### filter 함수를 사용하여 조건에 맞는 요소만 가져오기

In [56]:
def f(x):
  return 5 < x < 10

In [57]:
a = [8, 3, 2, 10, 15, 7, 1, 9, 0, 11]

In [59]:
list(filter(f,a)) #5보다 크고 10보다 작은 수만 출력

[8, 7, 9]

In [61]:
list(filter(lambda x: 5<x<10,a)) # 상기 함수와 같은 식을 lambd로 사용 하기

[8, 7, 9]

### find 함수 사용하여 이미지 파일만 가져오기
* find('찾을 내용') → 찾을 내용과 일치하는 문자열에 시작 인덱스를 반환 하고, 없을 시 -1을 반환한다.

In [62]:
files = ['font','1.png','10.jpg','11.gif','2.jpg','3.png','table.xlsx','spec.doc']

In [68]:
for idx,i in enumerate(files):
  if i.find('.png') != -1:
    print(f"{idx+1}번 {i} : {i.find('.png')}")

2번 1.png : 1
6번 3.png : 1

In [69]:
list(filter(lambda x: x.find('.png') != -1 or x.find('.jpg') != -1,files))

['1.png', '10.jpg', '2.jpg', '3.png']

In [8]:
DataUrl = 'https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv'
df = pd.read_csv(DataUrl,sep='\t')

In [9]:
df.head()

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18

In [10]:
df['t2_ban1'].apply(lambda x: x*2)

0        228
1         22
2        314
3        328
4        172
        ...
51485    110
51486    314
51487    226
51488    308
51489     22
Name: t2_ban1, Length: 51490, dtype: int64

In [7]:
import pandas as pd